<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="it">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Alcambraz -- {#TITLE#}</title>
    <link rev="made" href="mailto:EMAIL" />
    <link rel="shortcut icon" href="favicon.ico" />
    {#ALTERNATE#}
    <link href="$(ROOT)/css/site.css" rel="stylesheet" type="text/css" />
    <meta name="Keywords" content="programming, engineering, projects, free software, studio" />
    <meta name="Description" content="Lethalman's website" />
    <meta name="Generator" content="WML $(WML_VERSION)" />
    <meta name="Modified" content="$(WML_SRC_ISOTIME)" />
  </head>
  
  <body>
    <div id="page" class="centered">
      <div id="header">
        <ul>
          <li><a href="$(ROOT)/index.html">Home</a></li>
          <li><a href="$(ROOT)/about.html">About me</a></li>
          <li><a href="$(ROOT)/projects.html">Projects</a></li>
          <li><a href="$(ROOT)/articles.html">Articles</a></li>
        </ul>
      </div>
      <div id="main">
        {#BODY#}
      </div> <!-- main -->
      <div id="footer">
        <hr>
        Design and contents licensed under the <a href="http://creativecommons.org/licenses/by-sa/2.5/" target="_blank">CC Attribution-ShareAlike</a> terms.<br />
        This website has started being published since Sun Jun 21 2009.<br />
        Hosted at jooel.endofinternet.org.
      </div>
      
    </div> <!-- page -->
  </body>
</html>
{#BODY#:
