<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html lang="it">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Alcambraz | {#TITLE#}</title>
    <link rev="made" href="mailto:EMAIL" />
    <link rel="shortcut icon" href="favicon.ico" />
    {#ALTERNATE#}
    <link href="$(ROOT)/css/site.css" rel="stylesheet" type="text/css" />
    <meta name="Keywords" content="programming, engineering, projects, free software, studio" />
    <meta name="Description" content="Lethalman's website" />
    <meta name="Generator" content="WML $(WML_VERSION)" />
    <meta name="Modified" content="$(WML_SRC_ISOTIME)" />
  </head>
  
  <body>
    <div id="page" class="centered">
      <div id="header">
        <ul>
          <li><a href="$(ROOT)/index.html">home</a></li>
          <li><a href="$(ROOT)/projects.html">projects</a></li>
          <li><a href="$(ROOT)/articles.html">articles</a></li>
        </ul>
      </div>
      <div id="main">
        {#BODY#}
      </div> <!-- main -->
      <div id="footer">
        <hr>
        <br />
        <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/80x15.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/">Creative Commons Attribution-Noncommercial-Share Alike 3.0 License</a>.<br />
        This website has started being published since Sab 13 March 2010.<br />
        Hosted at <a href="http://www.000webhost.com/" target="_blank">000webhost.com</a>.
      </div>
      
    </div> <!-- page -->
  </body>
</html>
{#BODY#:
